  
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: flip it app infrastructure

Parameters:
  DomainName:
    Type: String
    Description: Domain Name
  Certificate:
    Type: String
    Description: ACM Certificate
  CallbackURL:
    Type: String

Resources:
  AppsUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UsernameAttributes:
        - email
      UserPoolName: "Mau Apps"
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true

  AppsPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: apps-pool-client
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      CallbackURLs:
        - !Ref CallbackURL
      LogoutURLs:
        - !Ref CallbackURL
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
      GenerateSecret: false
      UserPoolId: !Ref AppsUserPool
      WriteAttributes:
        - email
      ReadAttributes:
        - email
    
  AppsUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: "mauri-apps"
      UserPoolId: !Ref AppsUserPool



